import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { preview } from '../assets/preview.png'
import { getRandomPrompt } from '../utlits/index'
import { FormField, Loader } from '../components'


type Props = {}

interface FormState {
  name: string;
  prompt: string;
  photo: string;
}


const CreatePost = (props: Props) => {
  const navigate = useNavigate();
  const [form, setForm] = useState<FormState>(
    {
      name: '',
      prompt: '',
      photo: '',
    });

  const [generateImg, setGenerateImg] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(false);

  const handleSubmit = () => {

  }

  const handleChange = (e) => {

  }

  const handleSurpriseMe = () => {

  }

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[32px]'>
          Create
        </h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>
          Create a curated collection of creatively designed and visually captivating images generated by DALL-E AI and share them with the community.
        </p>
      </div>

      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormField
            labelName="Your Name"
            type="text"
            name="name"
            placeholder="John Doe"
            value={form.name}
            handleChange={handleChange}
          />
          <FormField
            labelName="Prompt"
            type="text"
            name="Prompt"
            placeholder="A surreal landscape with floating islands"
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}
          />
        </div>
      </form>
    </section>
  )
}

export default CreatePost