import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import preview from '../assets/preview.png'; 
import { getRandomPrompt } from '../utlits/index'
import { FormField, Loader } from '../components'


type Props = {}

interface FormState {
  name: string;
  prompt: string;
  photo: string;
}

const CreatePost = (props: Props) => {
  const navigate = useNavigate();
  const [form, setForm] = useState<FormState>(
    {
      name: '',
      prompt: '',
      photo: '',
    });

  const [generateImg, setGenerateImg] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(false);


  const generateImage = () =>{

  }

  const handleSubmit = () => {

  }

  const handleChange = (e:React.ChangeEvent<HTMLInputElement>) => {
    setForm({...form,[e.target.name]:e.target.value})
  }

  const handleSurpriseMe = () => {
    const randomPrompt = getRandomPrompt(form.prompt);
    setForm({...form, prompt: randomPrompt})
  }

  return (
    <section className='min-h-screen justify-center flex flex-col items-center max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[32px]'>
          Create
        </h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>
          Create a curated collection of creatively designed and visually captivating images generated by DALL-E AI and share them with the community.
        </p>
      </div>

      <form className='mt-16 max-w-3xl w-full' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormField
            labelName="Your Name"
            type="text"
            name="name"
            placeholder="John Doe"
            value={form.name}
            handleChange={handleChange}
          />
          <FormField
            labelName="Prompt"
            type="text"
            name="Prompt"
            placeholder="A surreal landscape with floating islands"
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}
          />
          
          <div className='relative bg-grey-50 border border-green-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center '>
            {
              form.photo?(
                <img src={form.photo} alt={form.prompt}
                className='w-full h-full object-contain' />
              ):(
                <img src={preview}
                alt='preview'
                className='w-full h-full object-contain opacity-40' />
              )
            }

            {
              generateImg &&(
                <div className='absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg'>
                  <Loader/>
                </div>
              )
            }
           
          </div>
        </div>

        <div className='mt-5 flex gap-5'>
            <button type='button'
            onClick={generateImage}
            className='text-white bg-green-700 font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center'>
              {generateImg ? 'Generating...' : 'Generate '}
            </button>
        </div>
        <div className='mt-10'>
              <p className='mt-2 text-[#666e75] text-[14px]'>
                Once you have created the image you want, you can share it with others with the community
              </p>

              <button type='submit' className='mt-3 text-white bg-[#6469ff] font-medium 
              rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center'>
              {loading ? "Sharing.... ": "Share with the community"}
              </button>
        </div>
      </form>
    </section>
  )
}

export default CreatePost