import React, { useState, useEffect } from 'react'
import { Loader,Card,FormField } from '../components'

type Props = {}

const Home = (props: Props) => {
  const [loading ,setLoading]=useState(false);
  const [allPost ,setAllPost]=useState(null);

  return (
    <section className='max-w-7xl mx-auto'>
      <h1 className='font-extrabold text-[32px]'>
        The Community Showcase
      </h1>
      <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>
      Explore a curated collection of creatively designed and visually captivating images generated by DALL-E AI.
      </p>
    </section>
  )
}

export default Home